Add SECRET_KEY_BASE to asset precompilation command
Fixes this error when deploying Whitehall:
ArgumentError: Missing secret_key_base for 'production' environment, set this string with rails credentials:edit